"""Generate docker-compose.serving.yaml from the serving catalog.

    uv run python scripts/gen_compose.py            # rewrite the file
    uv run python scripts/gen_compose.py --check    # exit 1 if the file is stale (used by tests)

One service per model, each on its own compose profile so
``docker compose --profile kokoro-82m up -d`` starts exactly one model.
"""

import sys
from pathlib import Path

from mlflow_registry.serving.catalog import CONTAINER_PORT, SERVING, SERVING_ALIAS, ServingSpec

OUT = Path(__file__).resolve().parents[1] / "docker-compose.serving.yaml"

HEADER = """\
# GENERATED by scripts/gen_compose.py from src/mlflow_registry/serving/catalog.py. Do not edit.
#
# Use together with the registry stack:
#   docker compose -f docker-compose.yaml -f docker-compose.serving.yaml --profile build build serving-base
#   docker compose -f docker-compose.yaml -f docker-compose.serving.yaml --profile kokoro-82m up -d --build
# or the wrapper: scripts/serve.sh build-base | build NAME | up NAME | down NAME | logs NAME | ps
#
# Each model is its own profile, so nothing here starts with a plain `docker compose up`.
# The 3090 (24 GB) cannot hold all nine at once; start what you need.

services:
  serving-base:
    image: mlflow-serving-base:latest
    build:
      context: .
      dockerfile: serving/Dockerfile.base
    command: ["true"]
    profiles: [build]
"""

SERVICE = """\

  serve-{name}:
    image: mlflow-serving/{name}:latest
    container_name: mr-serve-{name}
    build:
      context: .
      dockerfile: serving/Dockerfile.model
      args:
        MODEL: {name}
    profiles: [{name}]
    restart: unless-stopped
    depends_on:
      mlflow:
        condition: service_started
    environment:
      SERVING_MODEL_URI: models:/{name}@{alias}
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MODEL_CACHE: /models
      HF_HOME: /models/.hf
      MLFLOW_SCORING_SERVER_REQUEST_TIMEOUT: "600"
    volumes:
      - serving_models:/models
    ports:
      - "{port}:{container_port}"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:{container_port}/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 900s
"""

GPU = """\
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
"""

FOOTER = """\

volumes:
  serving_models:
"""


def render_service(s: ServingSpec) -> str:
    text = SERVICE.format(name=s.name, alias=SERVING_ALIAS, port=s.port, container_port=CONTAINER_PORT)
    return text + (GPU if s.gpu else "")


def render() -> str:
    return HEADER + "".join(render_service(s) for s in SERVING.values()) + FOOTER


def main(argv: list[str]) -> int:
    content = render()
    if "--check" in argv:
        if not OUT.exists() or OUT.read_text() != content:
            print(f"{OUT.name} is stale; run: uv run python scripts/gen_compose.py", file=sys.stderr)
            return 1
        return 0
    OUT.write_text(content)
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
